---
- hosts: all
  gather_facts: false

  tasks:
   - name: show run 
   ios_command:
   commands:
     - show run 
     host: "{{ ansible_host }}"
     register: config

  - name: save output to /etc/ansible/backups 
      copy: 
      content: "{{ config.stdout[0] }}"
      dest: "/etc/config-backup/show_run_{{ inventory_hostname }}.txt"
