---
- name: "Netflow Config"
  hosts: Core_Switches
  gather_facts: false

  tasks:
    - name: "Run Show Commands"
      ios_command:
        commands:
          - show run flow exporter
          - show run flow monitor
          - show run flow record
          - show flow interface | i Interface
      register: command

    - name: save output to file
      copy: 
        content: "{{ config.stdout[0] }}"
        dest: "/etc/misc-outputs/{{ inventory_hostname }}.txt"
