---
- hosts: all
  gather_facts: false
  
  tasks:
    - name: Update SNMP ACL
      ios_config:
        match: exact
        before: no ip access-list standard SNMP_ACL
        parents: ip access-list standard snmp.acl
        lines:
          - permit 10.10.25.70
          - permit 10.3.25.17

    - name: Update SNMP ios_config
      ios_config:
        #match: exact
        #before: no snmp-server community BB+pr1vat3 RW SNMP_ACL
        lines: snmp-server community BB+pr1vat3 RW snmp.acl
