---
- name: "Get interface Tunnel 4 Config"
  hosts: DMVPN-Routers
  gather_facts: true
  
  tasks:
    - name: Run Command
      ios_command:
        commands: 
          - show run aaa
      register: command_output

    - name: PRINT TO TERMINAL WINDOW
      debug:
        msg: "{{command_output.stdout}}"
