---
- name: "Get interface Tunnel 4 Config"
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Run Command
      ios_command:
        commands: 
          - show run int tunnel4

    - name: PRINT TO TERMINAL WINDOW
      debug:
        msg: "{{command_output.stdout}}"
